### ISSUE TITLE
Geoserver WMS layer animations in leaflet?

### ISSUE THREAD

**Issue by sharseema** [socib/Leaflet.TimeDimension#130]
I want to do animation of three Geoserver WMS layers, this three WMS layers from 1992,2002 and 2013 respectively. When animation starts first 1992 WMS layer will display after that 2002 and 2013 WMS layer appear as animation time lapse increases. I have tried in Leaflet but its not working. Can anyone have thought on this ?I tried with your examples,but my WMS layers are not display and also animation is not working and for time animation "Time not Available".
Is it possible to do Geoserver WMS or TIFF  layers with Leaflet Time Dimension. 
Thanks.

**Comment by rensa** [comment]
I have a WMS layer served from Geoserver working with Leaflet.TimeDimension now :) I'm not sure exactly what the problem is on your end, but a few problems I had included:

- Querying Geoserver's `wms/animate?` instead of the resular `wms`. This control is an _alternative_ to the Geoserver WMS animator.
- Forgetting to enable the time dimension for my layer in Geoserver (by selecting the layer in the `Layers` menu, going to the `Dimensions` tab and enabling the `Time` checkbox).
- Trying to add the static WMS layer as well as to the time layer (because I forgot to remove `.addTo(map)` from my static map).
- Trying to request invalid times. I just got blank white maps. Oops 😅 

If you want to see the state mine's in at the moment (on the client side; I can't show you the Geoserver side, obviously), it's [here](https://github.com/rensa/showcase-climdex/commit/210b9f877f1575dcf10b713a12663556daa185d7). Hope it helps!

**Comment by sharseema** [comment]
Sorry for late reply,thanks a lot ,but you provided link is not working.Thanks

**Comment by rensa** [comment]
Whoops, it was still a private repo. Should work now! (Again, though, since I'm running Geoserver locally the requests on't work on your end.)

**Comment by sharseema** [comment]
Thanks,yes link working now.

**Comment by sharseema** [comment]
Hi,
I tried example,but output getting black.What is parameter  "className: 'multiply-layer'" in geoserver URL.
I am trying to run it.

**Comment by rensa** [comment]
It's a  custom class that applies a CSS blending mode; you can turn it off. Once again, though, you won't get any actual output because the requests point to a local server I was running on the side.

**Comment by sharseema** [comment]
OK thanks,Actually i loaded my layers from local Geo-server  and run it on local machine but still not working.

**Comment by ISURU9900** [comment]
I'm runing the plugin with tiff images and it isn't working. It is giving me this error

            ncaught TypeError: Cannot read property 'querySelectorAll' of null
      at e._getDefaultTimeFromCapabilities (leaflet.timedimension.layer.wms.js:324)

and when markers are added to the map the error is,

           Uncaught TypeError: Cannot read property 'min' of undefined
        at e._loadData (leaflet.timedimension.layer.wms.timeseries.js:115)
        at e.addPositionMarker (leaflet.timedimension.layer.wms.timeseries.js:111)
        at e.<anonymous> (leaflet.timedimension.layer.wms.timeseries.js:32)
        at e.fireEvent (leaflet.js:6)
        at e._fireMouseEvent (leaflet.js:6)
        at HTMLDivElement.s [as _leaflet_dblclick2] (leaflet.js:8)
